"""Storage & communication provider interfaces (architecture 10.3).

Modules depend only on these protocols; the all-in-one runtime injects the
in-process/local implementations, the cluster deployment injects Redis/PG/NATS.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from whirlwind.core import (
    AgentDefinition,
    AgentSession,
    AgentVersion,
    CronJob,
    Sandbox,
    SessionEvent,
    Snapshot,
    SkillRef,
)
from whirlwind.core.events import Surface


@runtime_checkable
class MetadataStore(Protocol):
    """Slow-moving authoritative metadata: definitions, sessions, catalogues."""

    # -- agents / versions
    async def create_agent(self, agent: AgentDefinition) -> AgentDefinition: ...
    async def get_agent(self, agent_id: str) -> AgentDefinition | None: ...
    async def get_agent_by_name(self, name: str) -> AgentDefinition | None: ...
    async def list_agents(self) -> list[AgentDefinition]: ...
    async def update_agent(self, agent: AgentDefinition) -> AgentDefinition: ...

    async def create_version(self, version: AgentVersion) -> AgentVersion: ...
    async def get_version(self, version_id: str) -> AgentVersion | None: ...
    async def list_versions(self, agent_id: str) -> list[AgentVersion]: ...

    # -- sessions
    async def create_session(self, session: AgentSession) -> AgentSession: ...
    async def get_session(self, session_id: str) -> AgentSession | None: ...
    async def update_session(self, session: AgentSession) -> AgentSession: ...
    async def list_sessions(self, agent_id: str | None = None) -> list[AgentSession]: ...

    # -- sandboxes / snapshots
    async def upsert_sandbox(self, sandbox: Sandbox) -> Sandbox: ...
    async def get_sandbox(self, sandbox_id: str) -> Sandbox | None: ...
    async def list_sandboxes(self) -> list[Sandbox]: ...

    async def save_snapshot(self, snapshot: Snapshot) -> Snapshot: ...
    async def latest_session_snapshot(self, session_id: str) -> Snapshot | None: ...

    # -- triggers / resources
    async def save_cron(self, cron: CronJob) -> CronJob: ...
    async def delete_cron(self, cron_id: str) -> None: ...
    async def list_crons(self, agent_id: str | None = None) -> list[CronJob]: ...

    async def save_skill(self, name: str, version: str, archive: Path) -> SkillRef: ...
    async def skill_path(self, ref: SkillRef) -> Path | None: ...


@runtime_checkable
class KVStore(Protocol):
    """Hot dynamic state: route table, warm claims, singleflight locks."""

    async def get(self, key: str) -> str | None: ...
    async def put(self, key: str, value: str, *, ttl_s: float | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def cas(self, key: str, expected: str | None, new: str) -> bool: ...


@runtime_checkable
class SecretStore(Protocol):
    """Encrypted agent-env envelopes keyed by version (ADR-0010 D6).

    Values in and out are *envelope strings* (`v1:<key_id>:<b64>`), never
    plaintext — the store never sees a decryptable secret; decryption stays in
    `whirlwind/secrets.py` on the host side. `put_version_env` replaces the
    whole envelope set for the version (immutable version unit, no partial
    mutation).
    """

    async def put_version_env(self, version_id: str, envelopes: dict[str, str]) -> None: ...
    async def get_version_env(self, version_id: str) -> dict[str, str]: ...
    async def delete_version_env(self, version_id: str) -> None: ...


@runtime_checkable
class LockProvider(Protocol):
    """Distributed-lock-shaped primitive; in-process impl is a plain mutex set."""

    async def acquire(self, name: str, ttl_s: float = 30.0) -> bool: ...
    async def release(self, name: str) -> None: ...


@runtime_checkable
class ObjectStore(Protocol):
    """Large blobs: snapshot layers, harness artifacts."""

    async def put(self, key: str, src: Path) -> str: ...
    async def fetch(self, key: str, dest: Path) -> Path: ...
    async def delete(self, key: str) -> None: ...
    async def stat(self, key: str) -> dict[str, Any] | None: ...


@runtime_checkable
class EventLog(Protocol):
    """Append-only session event log. Owns per-session seq assignment."""

    async def append(
        self,
        session_id: str,
        type: str,
        data: dict[str, Any] | None = None,
        surface: Surface | None = None,
    ) -> SessionEvent: ...
    async def read(self, session_id: str, from_seq: int = 0, limit: int = 1000) -> list[SessionEvent]: ...
    async def last_seq(self, session_id: str) -> int: ...


@runtime_checkable
class EventBus(Protocol):
    """Fan-out bus for `sessions.{id}.stream`-style topics. At-least-once."""

    def publish(self, topic: str, payload: dict[str, Any]) -> None: ...
    async def subscribe(self, topic: str) -> Any: ...  # -> Subscription (async iterator)
